seed: 42
device: cuda:0
policy:
  init_noise_std: 1.0
  actor_hidden_dims: [512, 256, 128]
  critic_hidden_dims: [512, 256, 128]
  activation: elu
algorithm:
  {
    value_loss_coef: 1.0,
    use_clipped_value_loss: true,
    clip_param: 0.2,
    entropy_coef: 0.005,
    num_learning_epochs: 5,
    num_mini_batches: 4,
    learning_rate: 0.001,
    schedule: adaptive,
    gamma: 0.99,
    lam: 0.95,
    desired_kl: 0.01,
    max_grad_norm: 1.0,
  }
runner:
  {
    policy_class_name: ActorCritic,
    algorithm_class_name: PPO,
    num_steps_per_env: 24,
    max_iterations: 1500,
    empirical_normalization: false,
    save_interval: 50,
    experiment_name: anymal_c,
    run_name: "",
    resume: false,
    load_run: -1,
    checkpoint: -1,
    resume_path: None,
  }
